// Generated from xivdev/EXDSchema branch ver/2026.07.16.0001.0000; do not edit by hand.
// Field names are in row-offset order (EXDSchema convention); arrays are expanded.

pub const ITEM: &[&str] = &[
    "Singular",
    "Plural",
    "Description",
    "Name",
    "Adjective",
    "PossessivePronoun",
    "StartsWithVowel",
    "Unknown0",
    "Pronoun",
    "Article",
    "ModelMain",
    "ModelSub",
    "DamagePhys",
    "DamageMag",
    "Delayms",
    "BlockRate",
    "Block",
    "DefensePhys",
    "DefenseMag",
    "BaseParamValue[0]",
    "BaseParamValue[1]",
    "BaseParamValue[2]",
    "BaseParamValue[3]",
    "BaseParamValue[4]",
    "BaseParamValue[5]",
    "BaseParamValueSpecial[0]",
    "BaseParamValueSpecial[1]",
    "BaseParamValueSpecial[2]",
    "BaseParamValueSpecial[3]",
    "BaseParamValueSpecial[4]",
    "BaseParamValueSpecial[5]",
    "LevelEquip",
    "RequiredPvpRank",
    "EquipRestriction",
    "ClassJobCategory",
    "GrandCompany",
    "ItemSeries",
    "BaseParamModifier",
    "ClassJobUse",
    "Unknown2",
    "DefaultActionRange",
    "BaseParam[0]",
    "BaseParam[1]",
    "BaseParam[2]",
    "BaseParam[3]",
    "BaseParam[4]",
    "BaseParam[5]",
    "ItemSpecialBonus",
    "ItemSpecialBonusParam",
    "BaseParamSpecial[0]",
    "BaseParamSpecial[1]",
    "BaseParamSpecial[2]",
    "BaseParamSpecial[3]",
    "BaseParamSpecial[4]",
    "BaseParamSpecial[5]",
    "MaterializeType",
    "MateriaSlotCount",
    "SubStatCategory",
    "IsAdvancedMeldingPermitted",
    "IsPvP",
    "IsGlamorous",
    "AdditionalData",
    "StackSize",
    "PriceMid",
    "PriceLow",
    "ItemRepair",
    "ItemGlamour",
    "Icon",
    "LevelItem",
    "SubcategorySort",
    "ItemAction",
    "Cooldowns",
    "Desynth",
    "AetherialReduce",
    "Rarity",
    "FilterGroup",
    "ItemUICategory",
    "ItemSearchCategory",
    "EquipSlotCategory",
    "ItemSortCategory",
    "DyeCount",
    "CastTimeSeconds",
    "ClassJobRepair",
    "IsUnique",
    "IsUntradable",
    "IsIndisposable",
    "Lot",
    "CanBeHq",
    "IsCrestWorthy",
    "IsCollectable",
    "AlwaysCollectable",
];

pub const TERRITORYTYPE: &[&str] = &[
    "Name",
    "Bg",
    "ArrayEventHandler",
    "PlaceNameRegionIcon",
    "PlaceNameIcon",
    "Aetheryte",
    "FixedTime",
    "PlaceNameRegion",
    "PlaceNameZone",
    "PlaceName",
    "Map",
    "ContentFinderCondition",
    "BGM",
    "QuestBattle",
    "Resident",
    "NotoriousMonsterTerritory",
    "BattalionMode",
    "LoadingImage",
    "ExclusiveType",
    "TerritoryIntendedUse",
    "WeatherRate",
    "Unknown1",
    "ExVersion",
    "Unknown2",
    "ZoneSharedGroup",
    "AetherCurrentCompFlgSet",
    "MountSpeed",
    "IndividualWeather",
    "AchievementIndex",
    "Unknown6",
    "Unknown7",
    "PCSearch",
    "Stealth",
    "Mount",
    "Unknown8",
    "IsPvpZone",
    "Unknown9",
    "IsInUse",
    "Unknown11",
    "Unknown12",
    "Unknown13",
    "Unknown14",
    "Unknown15",
    "Unknown16",
    "Unknown17",
    "Unknown18",
];

pub const EQUIPSLOTCATEGORY: &[&str] = &[
    "MainHand",
    "OffHand",
    "Head",
    "Body",
    "Gloves",
    "Waist",
    "Legs",
    "Feet",
    "Ears",
    "Neck",
    "Wrists",
    "FingerL",
    "FingerR",
    "SoulCrystal",
];

pub const CLASSJOB: &[&str] = &[
    "Name",
    "Abbreviation",
    "NameFemale",
    "CanQueueForDuty",
    "NameEnglish",
    "ItemSoulCrystal",
    "UnlockQuest",
    "RelicQuest",
    "Prerequisite",
    "Unknown_70_1",
    "Unknown_70_2",
    "Unknown9",
    "ItemStartingWeaponMainHand",
    "ItemStartingWeaponOffHand",
    "ModifierHitPoints",
    "ModifierManaPoints",
    "ModifierStrength",
    "ModifierVitality",
    "ModifierDexterity",
    "ModifierIntelligence",
    "ModifierMind",
    "ModifierPiety",
    "Unknown2",
    "Unknown3",
    "Unknown4",
    "Unknown5",
    "Unknown6",
    "Unknown7",
    "LimitBreak1",
    "LimitBreak2",
    "LimitBreak3",
    "ClassJobCategory",
    "Unknown8",
    "JobIndex",
    "PvPBaseParamValue",
    "PvPActionSortRow",
    "PvPInitialSelectActionTrait",
    "ClassJobParent",
    "Role",
    "StartingTown",
    "PrimaryStat",
    "UIPriority",
    "StartingLevel",
    "PartyBonus",
    "JobType",
    "ExpArrayIndex",
    "BattleClassIndex",
    "DohDolJobIndex",
    "MonsterNote",
    "IsLimitedJob",
    "Unknown10",
];

pub const RACE: &[&str] = &[
    "Masculine",
    "Feminine",
    "RSEMBody",
    "RSEFBody",
    "RSEMHands",
    "RSEFHands",
    "RSEMLegs",
    "RSEFLegs",
    "RSEMFeet",
    "RSEFFeet",
    "Unknown0",
    "ExPac",
];

pub const TRIBE: &[&str] = &[
    "Masculine",
    "Feminine",
    "Hp",
    "Mp",
    "STR",
    "VIT",
    "DEX",
    "INT",
    "MND",
    "PIE",
];

pub const PLACENAME: &[&str] = &[
    "Name",
    "NameNoArticle",
    "Unknown0",
    "Unknown1",
    "Unknown2",
    "Unknown3",
    "Unknown4",
    "Unknown5",
    "Unknown6",
    "Unknown7",
    "Unknown8",
    "MapCondition",
];

pub const TERRITORYINTENDEDUSE: &[&str] = &[
    "Unknown0",
    "GayaSoundId",
    "ChatRule",
    "Unknown3",
    "EnableCrafting",
    "EnableGathering",
    "EnableRepairs",
    "EnableClassJobChange",
    "EnableClassJobChangeCombatJobCheck",
    "EnableJobChangeToLimitedJob",
    "EnableCompanion",
    "EnablePets",
    "EnableRidePillion",
    "DisableLogoutTimer",
    "EnableTeleport",
    "EnableReturn",
    "Unknown16",
    "Unknown17",
    "EnableRecommendList",
    "Unknown19",
    "Unknown20",
    "DisableMapDiscovery",
    "DisableFieldMarkers",
    "Unknown23",
    "EnableActions",
    "EnableConsumableItems",
    "Unknown26",
    "EnableTripleTriadMatches",
    "EnableTripleTriadMatchesAnywhere",
    "Unknown29",
    "Unknown30",
    "Unknown31",
    "CanPauseTimeWeather",
    "Unknown33",
    "EnablePvPQuickChat",
    "Unknown35",
    "Unknown36",
    "CanApplyGlamourPlatesAnywhere",
    "Unknown38",
    "EnableFieldMarkerPresets",
    "IgnoreCombatFlagForMarkers",
    "Unknown41",
    "Unknown42",
];

pub const EMOTE: &[&str] = &[
    "Name",
    "Icon",
    "UnlockLink",
    "TextCommand",
    "ActionTimeline[0]",
    "ActionTimeline[1]",
    "ActionTimeline[2]",
    "ActionTimeline[3]",
    "ActionTimeline[4]",
    "ActionTimeline[5]",
    "ActionTimeline[6]",
    "Order",
    "LogMessageTargeted",
    "LogMessageUntargeted",
    "Patch",
    "EmoteCategory",
    "EmoteMode",
    "HasMountedAnimation",
    "HasSwimmingAnimation",
    "HasDivingAnimation",
    "DontSetEmoteMode",
    "Unknown5",
    "UsableWhenFishing",
    "DrawsWeapon",
    "SheathesWeapon",
];

pub const ACTIONTIMELINE: &[&str] = &[
    "Key",
    "WeaponTimeline",
    "KillUpper",
    "Unknown_70",
    "Type",
    "Priority",
    "Stance",
    "Slot",
    "LookAtMode",
    "ActionTimelineIDMode",
    "LoadType",
    "StartAttach",
    "ResidentPap",
    "Unknown6",
    "Unknown1",
    "Pause",
    "Resident",
    "IsMotionCanceledByMoving",
    "Unknown2",
    "Unknown3",
    "IsLoop",
    "Unknown4",
];

pub const EMOTECATEGORY: &[&str] = &[
    "Name",
];

pub const AETHERYTE: &[&str] = &[
    "Singular",
    "Plural",
    "Adjective",
    "PossessivePronoun",
    "StartsWithVowel",
    "Unknown0",
    "Pronoun",
    "Article",
    "Unknown1",
    "Level[0]",
    "Level[1]",
    "Level[2]",
    "Level[3]",
    "RequiredQuest",
    "PlaceName",
    "AethernetName",
    "Territory",
    "Map",
    "AetherstreamX",
    "AetherstreamY",
    "Unknown2",
    "AethernetGroup",
    "Order",
    "IsAetheryte",
    "Invisible",
];

pub const LEVEL: &[&str] = &[
    "X",
    "Y",
    "Z",
    "Yaw",
    "Radius",
    "Object",
    "EventId",
    "Map",
    "Territory",
    "Type",
];

pub const MAP: &[&str] = &[
    "Id",
    "DiscoveryFlag",
    "MapMarkerRange",
    "SizeFactor",
    "PlaceNameRegion",
    "PlaceName",
    "PlaceNameSub",
    "TerritoryType",
    "OffsetX",
    "OffsetY",
    "DiscoveryIndex",
    "MapCondition",
    "PriorityCategoryUI",
    "PriorityUI",
    "MapType",
    "Unknown2",
    "MapReplace",
    "MapIndex",
    "DiscoveryArrayByte",
    "IsEvent",
    "Unknown1",
];

// Hand-added (2026-09-08) from the EXH column layout of game 2026.08.11; names follow Lumina.
pub const BGM: &[&str] = &[
    "File",
    "DisableRestartResetTime",
    "Priority",
    "SpecialMode",
    "DisableRestartTimeOut",
    "DisableRestart",
    "PassEnd",
];

pub const BGMSITUATION: &[&str] = &[
    "DaytimeID",
    "NightID",
    "BattleID",
    "DaybreakID",
    "TwilightID",
];

pub const BGMSWITCH: &[&str] = &[
    "Quest",
    "BGM",
    "Unknown0",
    "Unknown1",
];

/// Look up the embedded schema for a sheet name.
pub fn schema_for(sheet: &str) -> Option<&'static [&'static str]> {
    match sheet {
        "BGM" => Some(BGM),
        "BGMSituation" => Some(BGMSITUATION),
        "BGMSwitch" => Some(BGMSWITCH),
        "Item" => Some(ITEM),
        "TerritoryType" => Some(TERRITORYTYPE),
        "EquipSlotCategory" => Some(EQUIPSLOTCATEGORY),
        "ClassJob" => Some(CLASSJOB),
        "Race" => Some(RACE),
        "Tribe" => Some(TRIBE),
        "PlaceName" => Some(PLACENAME),
        "TerritoryIntendedUse" => Some(TERRITORYINTENDEDUSE),
        "Emote" => Some(EMOTE),
        "ActionTimeline" => Some(ACTIONTIMELINE),
        "EmoteCategory" => Some(EMOTECATEGORY),
        "Aetheryte" => Some(AETHERYTE),
        "Level" => Some(LEVEL),
        "Map" => Some(MAP),
        _ => None,
    }
}
