#!/usr/bin/env python3
"""Generate engines/ff11/src/gear_names.rs from xi-model-viewer's baked character list.

FFXI item DATs carry no model ids (the server sends them), so the names of equipment model
ids come from the community lists (AltanaViewer's List/PC/*.csv as re-baked into
xi-model-viewer's ui/public/lists/characters.json). Usage:

    tools/ff11_gear_names.py <path to characters.json> > engines/ff11/src/gear_names.rs
"""
import collections
import json
import re
import sys

SLOTS = ["face", "head", "body", "hands", "legs", "feet", "main", "sub", "range"]
# Look race numbers (the client's): the composer ids of the list mapped onto them.
RACES = {"HumeM": [1], "HumeF": [2], "ElvaanM": [3], "ElvaanF": [4], "Tarutaru": [5, 6], "Mithra": [7], "Galka": [8]}
JUNK = re.compile(r"^(NEW - mid|\d+/\d+$|None$|Invisible$)")


def main(path):
    data = json.load(open(path))
    # slot -> mid -> race -> label
    table = {s: collections.defaultdict(dict) for s in SLOTS}
    for race in data["races"]:
        looks = RACES.get(race["id"])
        if not looks:
            continue
        for slot in SLOTS:
            for item in race["slots"].get(slot, []):
                label = item["label"].strip()
                if JUNK.match(label):
                    continue
                for key, look in (("mid", looks[0]), ("midAlt", looks[-1])):
                    mid = item.get(key)
                    if mid is None:
                        continue
                    if slot == "face":
                        m = re.match(r"^(?:Taru (Male|Female) )?F(\d)([A-C])$", label)
                        if m:
                            label = f"Face {m.group(2)} {m.group(3)}"
                    table[slot][mid].setdefault(look, label)
    entries = []
    for si, slot in enumerate(SLOTS):
        for mid in sorted(table[slot]):
            by_race = table[slot][mid]
            counts = collections.Counter(by_race.values())
            common = counts.most_common(1)[0][0]
            entries.append((si, 0, mid, common))
            for look, label in sorted(by_race.items()):
                if label != common:
                    entries.append((si, look, mid, label))
    print("//! Names of FFXI equipment model ids per slot (generated by `tools/ff11_gear_names.py`")
    print("//! from the community character lists; the game's item files carry no model ids).")
    print("//! Entries: (slot index, look race or 0 for any race, model id, name).")
    print()
    print("pub const SLOTS: [&str; 9] = [" + ", ".join(f'"{s}"' for s in SLOTS) + "];")
    print()
    print("pub static NAMES: &[(u8, u8, u16, &str)] = &[")
    for si, look, mid, label in entries:
        label = label.replace("\\", "\\\\").replace('"', '\\"')
        print(f'    ({si}, {look}, {mid}, "{label}"),')
    print("];")
    print()
    print("/// Name of a model id in a slot for a look race (race-specific entries win).")
    print("pub fn gear_name(slot: &str, race: u8, model: u16) -> Option<&'static str> {")
    print("    let si = SLOTS.iter().position(|s| *s == slot)? as u8;")
    print("    let mut any = None;")
    print("    for (s, r, m, name) in NAMES {")
    print("        if *s != si || *m != model {")
    print("            continue;")
    print("        }")
    print("        if *r == race {")
    print("            return Some(name);")
    print("        }")
    print("        if *r == 0 {")
    print("            any = Some(*name);")
    print("        }")
    print("    }")
    print("    any")
    print("}")


if __name__ == "__main__":
    main(sys.argv[1])
